### ISSUE TITLE
MoveIT not executing plan on real stretch robot

### ISSUE THREAD

**Issue by shivani0812** [hello-robot/stretch_ros#60]
I am running MoveIt1 on the stretch robot but it is not able to execute the plan on the actual robot.

**Comment by hello-binit** [comment]
Hello @shivani0812, there is no support for running MoveIt1 on Stretch, as noted in the [package's README](https://github.com/hello-robot/stretch_ros/tree/master/stretch_moveit_config#hardware-integration). Instead, we are developing support for MoveIt2 on the actual robot. More details are available in this [forum post](https://forum.hello-robot.com/t/errors-bringup-controller/334/2?u=bshah).

**Comment by praveenVnktsh** [comment]
hey @hello-binit , just wanted to know if this is fixed, or if there is any workaround to getting moveit working with stretch re1.

**Comment by hello-binit** [comment]
Hi @praveenVnktsh, we won't be supporting MoveIt1 since the algorithms for diff drive mobile base planning aren't available. MoveIt2 is supported on both Stretch RE1 and RE2. If you haven't already, you can [upgrade your Stretch RE1 to Ubuntu 20.04](https://docs.hello-robot.com/0.2/stretch-install/docs/robot_install/) and [start using ROS2 and MoveIt2](https://docs.hello-robot.com/0.2/stretch-tutorials/ros2/moveit_basics/), which is capable of full body planning for Stretch.
