### ISSUE TITLE
Distributing compiled URDF files?

### ISSUE THREAD

**Issue by stephane-caron** [hello-robot/stretch_ros#98]
Hello and thanks for maintaining this repository :smiley: 

I was wondering if you would consider distributing compiled URDF files alongside Xacro files?

Distributing URDF files is common in open source robot descriptions on GitHub. For instance, in the [Awesome Robot Descriptions](https://github.com/robot-descriptions/awesome-robot-descriptions) list, 57 / 79 descriptions are URDF while 9 / 79 are Xacro-only.

Distributing URDF also makes it one-shot to load the robot description in popular (non-ROS) software such as Pinocchio and PyBullet, for instance via [robot_descriptions.py](https://github.com/robot-descriptions/robot_descriptions.py):

```python
from robot_descriptions.loaders.pinocchio import load_robot_description

stretch = load_robot_description("stretch_description")
```

Right now this snippet will load the description from [this repository](https://github.com/robot-descriptions/stretch_description), but it would be better if it would load the description straight from the official repository.

**Comment by hello-binit** [comment]
Hi @stephane-caron, thanks for raising this request. I'd like to provide a little bit of context on why we've stuck to XACROs and haven't included compiled URDFs in the Stretch Description package yet, and perhaps hear your thoughts on how we can make it easier for simulators like Pinocchio/PyBullet to import Stretch's URDF.

First, there are two models of Stretch to date: Stretch RE1 (began shipping summer 2020) and Stretch 2 (began shipping summer 2022). The two models are kinematically identical, so the URDFs are very similar but the meshes are different. Here's what the [Stretch 2](https://hello-robot.com/stretch-2) looks like visually:

![stretch 2](https://user-images.githubusercontent.com/64861565/234500898-be19299d-c853-4dfb-983d-c6dd86e4353b.png)

It would be relatively easy to distribute a URDF for each model, but the reason I bring this up is because I noticed the [robot-descriptions/stretch_description](https://github.com/robot-descriptions/stretch_description) repo seems to be missing a URDF for the newer Stretch 2 model.

Second, there are multiple end-effectors available for Stretch and it's generally very easy to swap between them. The two most popular, the [Stretch Compliant Gripper](https://hello-robot.com/stretch-2#stretch-compliant-gripper-re2) and the [Stretch Dex Wrist](https://hello-robot.com/stretch-dex-wrist) are shown here:

Stretch Compliant Gripper             |  Stretch Dex Wrist
:-------------------------:|:-------------------------:
![standard gripper](https://user-images.githubusercontent.com/64861565/234503033-bea5ea26-10c1-4fad-bbb0-ab6a0f297ca7.png)  |  ![dex wrist](https://user-images.githubusercontent.com/64861565/234502212-ceb48380-f187-4959-932b-bebd1c775eab.png)

Beyond these two, there's end-effector tools for [USB cameras](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/wrist_USB_board_camera), [tablets](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/swivel_tablet_mount), [phones](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/phone_holder_V1), [dry erase markers](https://github.com/hello-robot/stretch_tool_share/blob/master/tool_share/dry_erase_holder_V1), [Swiffers](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/swiffer_mount_V1), [ReactorX wrist](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/reactorx_wrist_V1), and a [cup tray](https://github.com/hello-robot/stretch_tool_share/tree/master/tool_share/tray_cup_holder_V1). These tools come with their own XACROs and meshes, and we've provided [instructions](https://github.com/hello-robot/stretch_ros/tree/master/stretch_description#changing-the-tool) for swapping in the correct XACRO for the attached tool in order to allow users to compile the URDF as needed. If we were to include compiled URDFs in Stretch Description, we would need to either include one for each tool (although new tools are created frequently) or select a subset of the tools for which to provide the compiled URDFs. One URDF cannot include all the tools available to use with Stretch.

Third, the two gripper tools, the Stretch Compliant Gripper and Stretch Dex Wrist are "compliant" grippers. [This video](https://youtu.be/N0122E_ZLmM) shows how the grippers deforms around the object to provide a very sturdy grip on the object. To date, URDFs only support a few types of joints (e.g. revolute, prismatic, etc.) between rigid links. Some simulators have support for deformable links, however, you would have to carefully characterize the bend of the gripper's spring steel in order to create a simulation with high fidelity to the real grippers.

![unrealistic gripper](https://user-images.githubusercontent.com/64861565/234509117-ea529f75-7ea0-49cb-869d-c66e140ccc80.png)

At the moment, the two fingers in these tools are modeled as two rigid fingers with revolute joints that can move independently of each other. If the Pinocchio/PyBullet simulation of Stretch were to import a compiled URDF with this model of the fingers, the grasping fidelity would be poor and any learned policy would transfer to the real robot poorly.

Fourth, and finally, Stretch robots ship from the factory with "calibrated" URDFs, where the link offsets and backlashes are calibrated by the robot looking at itself and detecting the Aruco markers on itself. The [open source calibration software](https://github.com/hello-robot/stretch_ros/tree/master/stretch_calibration) aggregates a dataset of detections from a variety of robot configurations in order to optimize a solution for the URDF's offsets and backlashes. This calibration plays a large part in enabling Stretch to successfully grasp objects in the environment and deal with "hand eye misalignment". Here's what the difference looks like:

![aligned point cloud w/robot](https://user-images.githubusercontent.com/64861565/234511254-318dcbd9-f7fd-4841-96e8-507f16d0503a.png)

Each calibrated URDF is unique to a Stretch. Likely, any policy learned on a simulated Stretch would have a better chance of transferring over to the real Stretch if the simulated Stretch were based on the calibrated URDF.

Hopefully, this helps provide context on some of the concerns with providing a compiled URDF of Stretch. It is my expectation that handling these "gotchas" is important if we want simulations of Stretch to accurately simulate how the real robot behaves in the world.

**Comment by stephane-caron** [comment]
Thank you @hello-binit for sharing this context!

Regarding the Stretch 2 model:

> It would be relatively easy to distribute a URDF for each model, but the reason I bring this up is because I noticed the [robot-descriptions/stretch_description](https://github.com/robot-descriptions/stretch_description) repo seems to be missing a URDF for the newer Stretch 2 model.

Absolutely, I don't have ROS installed and setting up an environment where ``xacro`` runs would be too much of a sidetrack for now. But I'd gladly merge PRs for other models if that's helpful.

I understand your technical decision in light of having configurable end-effectors and a calibrated robot model. In Pinocchio or iDynTree one can customize the robot model at runtime after loading e.g. a base URDF, but it is indeed a pro of xacro to be able to separate (1) configuration/calibration/compilation from (2) execution.

From my point of view it wouldn't hurt to provide a sample URDF for testing and sharing ROS-free code (e.g. this example of [weighted inverse kinematics with Stretch RE1](https://github.com/tasts-robots/pink/blob/master/examples/mobile_stretch.py) just checks that the algorithm work, which doesn't require a calibrated model), but I understand from a support point of view there may be other arguments against it (e.g. if a pre-compiled URDF is available, new users could be tempted to skip calibration and just use it).

I'll be closing this issue :ok_hand:
