### ISSUE TITLE
Can't find the stretch moveit-config

### ISSUE THREAD

**Issue by MughniIrfan** [hello-robot/stretch_ros#99]

**Comment by hello-binit** [comment]
Hi @AbdulMughniKUCAR, the "stretch_moveit_config" package was removed in commit https://github.com/hello-robot/stretch_ros/commit/fba00a3d37871759bdf2cc5dbd73aaaa02dee6ae since it was confusing users. The "stretch_moveit_config" package only allowed users to use MoveIt1 with a **Gazebo simulated** Stretch and there has not been support for MoveIt1 on a real Stretch robot. Since the package name "stretch_moveit_config" was confusing users into thinking they could use MoveIt1 on a real Stretch robot, we decided to delete the package.

The other reason we decided to delete the package is because Stretch now has native [MoveIt2 support in it's ROS2 packages](https://github.com/hello-robot/stretch_ros2/tree/galactic/stretch_moveit2). MoveIt2 is the successor to MoveIt1, and includes improvements, such as support for diff drive planning for Stretch's mobile base. If you are looking to use MoveIt on a real Stretch, I recommend trying the [Stretch MoveIt2 tutorials](https://docs.hello-robot.com/0.2/stretch-tutorials/ros2/moveit_basics/).

Hope this helps and let me know if you have any additional questions.

**Comment by MughniIrfan** [comment]
Hi Binit,

We received the Stretch robot last week and I want to do some basic
grasping demos for my team at the university.

The robot has ROS Noetic installed and the Movit packages are missing from
there too.

Can we talk about this on teams?

Thanks,

Abdul Mughni
Khalifa University (KUCARS)

**Comment by hello-binit** [comment]
Hi @AbdulMughniKUCAR , yes, that package was deleted from ROS Melodic and ROS Noetic. Moveit support is only available for Stretch in ROS2 Galactic.

Happy to answer your questions on a video call. Please send an email to support@hello-robot.com, so we can schedule the meeting.
